version: "3.7"
services:
  laravel:
    build:
      args:
        user: chris
        uid: 1000
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: coffeesound_laravel
    container_name: coffeesound-laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - coffeesound

  database:
    image: mysql:5.7
    container_name: coffeesound-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: coffeesound
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: chris
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - coffeesound

  nginx:
    image: nginx:alpine
    container_name: coffeesound-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - coffeesound

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: coffeesound-phpmyadmin
    links:
      - database
    ports:
      - 9191:80
    environment:
      PMA_HOST: database
      MYSQL_USER: chris
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - database
    networks:
      - coffeesound

  angular:
    container_name: coffeesound-angular
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - './frontend:/app'
      - './frontend/node_modules'
    ports:
      - 4201:4200
    networks:
      - coffeesound

  test:
    container_name: coffeesound-test
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    networks:
      - coffeesound
    tty: true

networks:
  coffeesound:
    driver: bridge
